### ISSUE TITLE
Canvas goes black on switch tab

### ISSUE THREAD

**Issue by bdrobinsonbbc** [bbc/VideoContext#13]
Sometimes when I switch away from and then come back to the tab with the VideoContext, the canvas goes black.

In the snippet below, the video is paused after 2 seconds by setting `stretchPaused=true`. Once it has paused, if you move to a different tab for more than 8 seconds (the video's stop time (10 seconds) minus the video's current time (2 seconds)) the canvas goes black when you return to the tab. The issue doesn't seem to be there if the stop time is not set.

``` js
var canvas = document.getElementById("canvas");

var videoCtx = new VideoContext(canvas);
var node = videoCtx.createVideoSourceNode("./video.mp4");

node.start(0);
node.stop(10);
node.connect(videoCtx.destination);

videoCtx.play();

setTimeout(function() {
    node.stretchPaused = true;
}, 2000);
```

**Comment by MatthewShotton** [comment]
Hi Ben,

This problem was due to the requestAnimationFrame loop not happening when the tab lost visibility.

The VideoContext now falls back to using a web-worker to run the update loop when visibility is lost and then switching back to a requestAnimationFrame loop when visibility is re-gained.

The webworker is used over a simple setInterval or setTimeout loop because the resolution of these functions can be greatly reduced when a tab is backgrounded, see: http://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome

This issue should now be fixed in v0.19.1.

Kind regards,
Matt
