### ISSUE TITLE
demo is no working in mobile's chrome browser

### ISSUE THREAD

**Issue by fomenyesu** [bbc/VideoContext#16]
hi,
I am checking your example, and it can't work in mobile  chrome . Here is the error in console:

Uncaught TypeError: Array.from is not a function
85  videocontext.js:641   Uncaught TypeError: Array.from is not a function

Am I missing something ?  Or it's no support in mobile yet?

thank you !

**Comment by MatthewShotton** [comment]
Hi,

Thank you for raising this. That error looks like it's due to a missing polyfill for "Array.from" in the es6 to es5 conversion step.That specific error should be fixed in commit 808f6b627f08dcdae2aa535cbae99125ebbf93bb which is published to npm as version 0.23.0.

We don't currently actively support mobile. A discussion about this can be found in issue #14 . It boils down to the requirements on mobile for a video element to have its play method called by a user initiated action. This means the VideoContext is unable to automatically trigger video playback in normal operation. There is a discussion in issue #14 about a potential work-around which involves creating a number of video elements which don't have any src attribute set up front and calling "play()" on all of them during the initial user action to start the video context playback. This puts the elements into a state where they can be controlled automatically, then passing those elements in when calling createVideoSourceNode().

Kind regards,
Matt

**Comment by MatthewShotton** [comment]
VideoContext should now work with chrome on mobile.
