### ISSUE TITLE
do something in videoContext end function

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#26]
this.ctx.registerCallback('ended', this.hanldeEnded);
hanldeEnded = () => {
    console.log('====>Playback ended');
    this.ctx.pause();
    this.ctx.currentTime = 0;
}

the console.log is show but this.ctx is still playing form 0s last for a few seconds, and frame is not show, i saw videoNode registerCallback is still loading

**Comment by MatthewShotton** [comment]
Hi Statfine,

Thanks for finding this one! It looks like there's a bug in the order in which operations happen internally in the VideoContext, the underlying video element for the videoNode was not having pause() called on it until after the "ended" callback had been triggered, and because the pause, and update to currentTime where happening in the callback the videoNode never properly entered its ENDED state.

I've pushed a potential fix for this which should be available from npm as v0.33.3. Let me know if it fixes the issue you're seeing.

Kind regards,
Matt

**Comment by Statfine** [comment]
thanks ,it's all right
