### ISSUE TITLE
source empty

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#28]
this.ctx = new VideoContext();
var videoNode = this.ctx.createVideoSourceNode('video.mp4');
videoNode.start(0);
videoNode.stop(10);
var videoNode2 = ctx.createVideoSourceNode('');
videoNode2.start(10);
videoNode2.stop(20);

![4a8d654a-c16e-48aa-bec6-0467eb9c5bdf](https://cloud.githubusercontent.com/assets/4608910/24140618/afc6e75e-0e5b-11e7-95fa-f19fc55d2c6f.png)
In this code the this.ctx.duration is 20s,
i want to show 20s video and the last 10s has no content(during 10s~20s i want listen in nocontent callback) but it looks like something wrong leads to videocontext is not continue after 10s.

**Comment by MatthewShotton** [comment]
Hi!

The reason the it won't work is the VideoContext doesn't treat the node as not having content, it treats it as having invalid content, as it will try and load the video a the given url (and empty string), and then break because it can't decode anything.

You can achieve a similar thing in a number of ways. 

This example uses "endOnLastSourceEnd" which makes the duration of the VideoContext Inifinity, so you have to manually stop the playback of the VideoContext when you reach the point you want it to finish. But will cause a nocontent callback to be triggered when the first video finishes playing.

``` JavaScript
var canvas = document.getElementById("canvas");
var ctx = new VideoContext(canvas, undefined, {"endOnLastSourceEnd":false});

var vid = ctx.video("./video.mp4");
vid.start(0);
vid.stop(10);
vid.connect(ctx.destination);

ctx.registerCallback("nocontent", ()=>{
    console.log("No Content");
});

ctx.registerTimelineCallback(20,()=>{
    console.log("Stopping VideoContext");
    ctx.pause();
});

```

The next method uses a transparent png image as the filler content, and instead of listening for nocontent, you listen to the play event of the filler image.

``` JavaScript
var canvas = document.getElementById("canvas");
var ctx = new VideoContext(canvas);

var vid = ctx.video("./video.mp4");
vid.start(0);
vid.stop(10);
vid.connect(ctx.destination);

var img = ctx.image("./blank.jpg"); //blank.png is a transparent png image
img.start(10);
img.stop(20);
img.connect(ctx.destination);

img.registerCallback("play", ()=>{
    console.log("No Content");
});
```
Hopefully one of them meets your requirements?

Kind regards,
Matt

**Comment by Statfine** [comment]
Thank you for your answer，
both two methods are ok;i will choose the second method in my project, because i need ctx.duration in video time control and accurate selection time
