### ISSUE TITLE
can this do some anti-aliasing ?

### ISSUE THREAD

**Issue by tinybug** [bbc/VideoContext#31]
When I use this to play video, it look like this:
<img width="497" alt="46e41c93-c9ce-4a9b-8d08-c2f6768aa6a1" src="https://cloud.githubusercontent.com/assets/3439875/24238260/a7b069a2-0fe4-11e7-90b8-20db9141cf9f.png">
When I go to https://www.shadertoy.com/view/Mdf3zr, play the same video(comment the 39 line of the glsl script), it look like this:
<img width="1190" alt="b918cf52-e8d6-43af-9ad4-13bd3d6d1c20" src="https://cloud.githubusercontent.com/assets/3439875/24238306/d458c602-0fe4-11e7-8752-1cc813c1dbcd.png">

Can VideoContext do some anti-aliasing to let the video look more smoothly?

[shadertoy.com use piLibJs(http://www.iquilezles.org/code/piLibsJS/piLibsJS.htm) for rendering, but it's too complex for me...😭]

**Comment by MatthewShotton** [comment]
Hi!

Thanks for raising this! We've seen this crop up before. The problem arises because there's 3 different resolutions in play. There's the resolution of the source video, the resolution of the canvas element the video context renders too, and the display resolution on page the canvas element is being set to by css.

The current way we fix this is to set the canvas size to the video size. Then use css/style attributes to set the display size for the canvas.


```JavaScript
var canvas = document.getElementById("cavnas");
//Set the canvas drawing buffer to the resolution of the video
canvas.width = 640;
canvas.height = 360;

//Set the canvas display dimensions to how big you want it displayed on page.
// (You can do this via CSS or like this)
canvas.style.width = "720px";
canvas.style.height = "405px";

var ctx = new VideoContext(canvas);
var video = ctx.video("video.mp4");
video.connect(ctx.destination);
ctx.play()
```

This works because the browsers style engine does a much better job at anti-aliasing than the VideoContext can do in a shader (currently).

The downside to this approach is all your videos need to be the same resolution to look good.

Hopefully that provides you with a usable solution?

Kind regards,
Matt

**Comment by tinybug** [comment]
@MatthewShotton Thanks for replying ! It look good to apply your solution, but my videos have variety resolution, I will go to find out how shadertoy to fix this issue in spare time, and then replay you after I find out the answer.😊

**Comment by tinybug** [comment]
@MatthewShotton shadertoy.com base on the same resolution you gave, thanks a lot for this!😄

**Comment by MatthewShotton** [comment]
@tinybug ahh! thanks for finding out. That's really good to know.
