### ISSUE TITLE
Expose the duration of the videoNode

### ISSUE THREAD

**Issue by barata0** [bbc/VideoContext#33]
Hi,

I need to add 2 clips in a row on a timeline. But I don't know in advance the durations.

```
videoNode1 = videoCtx.video(url1);
videoNode1.startAt(0);
videoNode1.stopAt(???); // video1FullDuration
videoNode1.connect(videoCtx.destination);
videoNode2 = videoCtx.video(url2);
videoNode2.startAt(???); // video1FullDuration
videoNode1.stopAt(???); // video1FullDuration + video2FullDuration
videoNode2.connect(videoCtx.destination);

```

How to query for the VideoNode full duration (maybe even if it is not connected to any context)?

**Comment by MatthewShotton** [comment]
Hi @barata0 

The video context doesn't know the duration of a video node until it has been loaded, and it won't get loaded until about 4 seconds before it has to play. This is to prevent multiple simultaneous requests being sent when the VideoContext is initialised and a page becoming unresponsive.

Fortunately the VideoContext provides some callbacks which can help! To achieve what you want you should be able to do something like the following:

```
videoNode1 = ctx.video("video1.mp4");
videoNode1.startAt(0);
videoNode1.connect(ctx.destination);

videoNode1.registerCallback("loaded", ()=>{
    videoNode2 = ctx.video("video2.mp4");
    videoNode2.startAt(videoNode1.duration);
    videoNode2.connect(ctx.destination);
});
```

It's worth noting a video nodes stop time will automatically be set (if one hasn't manually been set) once a video node has loaded the underlying video and figured out it's duration. Which is why the above code has no stopAt or stop calls in it.

Hope that's helpful?

Kind regards,
Matt
