### ISSUE TITLE
Best way to clean

### ISSUE THREAD

**Issue by barata0** [bbc/VideoContext#37]
Hi,

What is the best way to clean a video context timeline? I mean removing all the videos and effects (or destroy and create again)?

Thnks

**Comment by MatthewShotton** [comment]
Hi @barata0,

Thanks for raising this. I've just added two new experimental methods for helping clean up a VideoContext.

Every node (image, video, effect, etc) now has a ```destroy()``` method which will completely disconnect it from the processing graph and clean up it's callbacks and internals. Once destroy has been called on a node it can no longer be used in any way and all references to it should be discarded.

The VideoContext now also has a ```reset()``` method, which as well as automatically calling destroy on all nodes will also remove all callbacks registered to the VideoContext.

I haven't tested all edge cases for these two new methods so please feel free to raise any issues if you have trouble.

These changes are now in VideoContext release 0.35.0 which has been pushed to npm.

Cheers!

**Comment by gossi** [comment]
That helps a lot 👍 

I was a bit wondering about calling the method on VideoContext `reset()`. That might be misleading in a way, that it will probably reset playback to start and remove all the noise that probably got a long the recent playback. I would also go with `destroy()` on VideoContext, which passes the call down to all connected nodes. Since VideoContext is unusable to what it was configured before, it'd be wise to better start with a fresh `new VideoContext()` instead ;)
