### ISSUE TITLE
Warning: "WebGL: INVALID_VALUE: texImage2D: no video"

### ISSUE THREAD

**Issue by gossi** [bbc/VideoContext#60]
I do get this warning fairly often, populating my console: `WebGL: INVALID_VALUE: texImage2D: no video`

I tracked it down to the function:

https://github.com/bbc/VideoContext/blob/5259e470e740d351e569a49ea665f1f865ff3d2e/src/utils.js#L63-L67

Background: I do have parts of my videocontext, which are black (nothing to show at that time). I also see this, when the video is loading.

**Comment by MatthewShotton** [comment]
Hi @gossi thanks for raising this! This has been an issue for ages. I've published a fix in v0.51.2.

The problem was elements being passed into that function which weren't fully loaded and ready to display.  I've added a guard for the elements readyState at the top of the function which should hopefully mitigate this.

Let me know if you still see the warning during the parts of your VideoContext instance which are black.

**Comment by gossi** [comment]
looks fine now :)

**Comment by bitcloudTheFirst** [comment]
Hi, this may still be an issue in certain circumstances (unless I'm doing it wrong)

Connecting audio elements to the canvas works, but it tries to attach a texture, and you get this warning again. I can't figure out how to check for this. Is there a known fix?

**Comment by PTaylour** [comment]
It doesn't sound like you're doing anything wrong.

Do you see the issue with a simple graph like this?

`Audio -> destination`

**Comment by dedurus** [comment]
Please check a workaround in #216
