### ISSUE TITLE
[Question] - Moving to a web worker?

### ISSUE THREAD

**Issue by byronmejia** [bbc/VideoContext#63]
Hey friends, has anyone had luck moving VideoContext to a web worker? Would it be something worth while doing?

**Comment by MatthewShotton** [comment]
Hey @byronmejia,

Interesting idea!

The big processing cost in VideoContext at the moment as the uploading of video/image textures to GPU memory. This is made worse by the fact that the textures are uploaded more frequently than they need to be.

The reason for this is there's no callback on a video element for when a new frame is available, so the VideoContext uploads new textures as fast as the requestAnimationFrame loop at the heart of the VideoContext can run. This is a compromise, and means occasionally a frame is skipped if the browser is under heavy load, and sometimes there is the same frame uploaded multiple times, needlessly consuming CPU.

If a WebWorker could get direct access to the WebGL context and shift this repetitive updating of the texture memory into a  separate thread away from the main one it'd hopefully speed things up in the main thread a fair amount.

I've had a quick look into this and it seems for the time being WebGL is only accessible from the main thread. There's a few tricks where people have tried to get around this by creating an API which passes [WebGL calls from a WebWorker through to the main thread](https://research.mozilla.org/2014/07/22/webgl-in-web-workers-today-and-faster-than-expected/) but i suspect in this would still mean the heavy texture upload operation is still happening on the main thread, it's just being triggered from the WebWorker.

There also seems to be support for direct [WebGL access in a WebWorker in firefox](https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/) but I'm not sure WebWorkers can get access to the image buffer of a video element in order to upload it to texture memory.

All that said, there might be lesser but still significant operations in the VideoContet which could be shifted to a WebWorker to help speed things up.

**Comment by byronmejia** [comment]
That's so cool! Thanks for the information, @MatthewShotton - I'll take a gander the next few weeks.
