### ISSUE TITLE
playbackRate case currentTime is  not video currentTime

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#88]
The video duration is 15s, If I set playbackRate to 2X. Is currentTime is VideoContext  play time not the video currentTime？Video is played with 8s( video has ended in 8s)，VideoContext currentTime is 8s but native video currentTime is 15s
`  
const node = this.ctx.video(src, 0, 4, { volume: 0.8, loop: true, playbackRate: 2 });
 node.startAt(0);
node.stopAt(15);`

VideoContext will play 15s and play video twice

is it right？

**Comment by PTaylour** [comment]
I believe this is by design.

The time argument provided to the`startAt` & `stopAt` methods refer to the points on the global ctx timeline at which you'd like to start and stop node playback.

In your example you have set the local playback rate of the node to 2, but the global playback rate of the ctx is still 1 ([to set this you use this method](https://github.com/bbc/VideoContext/blob/master/src/videocontext.js#L342-L370)). The video element clock is set to run twice the speed of the ctx, causing the video to play twice.

As the node playbackRate effects the duration of the video, you'll need to account for that when setting points on the ctx timeline. 

In your example the duration is `15 / 2`, so to play back the video once, starting at time `t` you'd write: `node.startAt(t); node.stopAt(t + 15 / 2)`.

If you'd like all nodes to playback at x2 you could set the global playback rate.

```
this.ctx.playbackRate = 2;
const node = this.ctx.video(src, 0, 4, { volume: 0.8, loop: true });
node.startAt(t);
node.stopAt(t + 15);
```

Here the ctx and element timelines playback at the same rate, so you don't need to divide the duration by 2.


Does that help?

**Comment by Statfine** [comment]
Your answers are very useful to me；
change my code like this, and all is right
```
 const playRate = 1; // 0.5 2
 this.ctx.playbackRate = playRate;
 const node = this.ctx.video(src, 0, 4, { volume: 0.8, loop: false,   playbackRate: playRate });
```
